[package]
name = "contract"
version = "0.1.0"
edition = "2021"
 
[lib]
crate-type = ["cdylib"]
 
[dependencies]
cosmwasm-std = { version = "2.1.4", features = ["staking", "cosmwasm_2_0"] }
cw-storage-plus = "2.0.0"
serde = { version = "1.0.214", default-features = false, features = ["derive"] }